[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["python3", "gnumake", "gcc"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate && node scripts/build-fix.js"]

[start]
cmd = "npm start"
