[phases.setup]
aptPkgs = ["python3", "make", "gcc", "g++"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate && node scripts/build-fix.js"]

[start]
cmd = "npm start"
